DS-1758-logical-types Add logical types date, time, datetime, uuid an…
waveaccounting/avro-to-python-types pull request #14
Opened 2021-03-08 15:18 UTC by wcn00

Add the logical values defined in the avro schema to the TypedDict classes generated by this project.  Except for the microsecond values, which we don't (at present) anticipate using.
[https://avro.apache.org/docs/current/spec.html](https://avro.apache.org/docs/current/spec.html)
They are:
date
time
datetime
uuid
Decimal

2021-03-08 18:46 UTC, dangreenisrael commented on avro_to_python_types/schema_mapping.py
> +    "date": "datetime.date",
I don't think that these will correctly map.

AFIK, a the `date` type is represented in avro as an `int`, whereas `datetime.date` is a class that takes `year, month, day` in its constructor.

https://docs.python.org/3/library/datetime.html#datetime.date

What if we represent these dates with just an `int` for now?

2021-03-08 18:48 UTC, dangreenisrael commented on avro_to_python_types/schema_mapping.py
> +    "uuid": "uuid.uuid4",
I believe that `uuid.uuid4` is a function that generates a UUID. I think we may need to just use a string for this.

2021-03-08 18:51 UTC, dangreenisrael commented
For the cases where we are forced to use `int` or `string` for logical types, we could also create a custom type. But in order to avoid having the same type redefined, we may need to jump through some hoops that may be out of scope for this issue.

2021-03-08 19:14 UTC, Tarun-S commented on avro_to_python_types/schema_mapping.py
> +    "date": "datetime.date",
I found this interesting page: https://marcosschroh.github.io/dataclasses-avroschema/complex_types/

Doesn't include dates, but might be helpful in the future.

2021-03-08 19:14 UTC, Tarun-S commented on avro_to_python_types/schema_mapping.py
> +    "date": "datetime.date",
Looks like there's a table for datetime stuff too: https://marcosschroh.github.io/dataclasses-avroschema/logical_types/

2021-03-08 19:16 UTC, Tarun-S commented on avro_to_python_types/schema_mapping.py
> +    "date": "datetime.date",
The above author's project does the reverse of this project:

https://github.com/marcosschroh/dataclasses-avroschema/

2021-03-08 19:18 UTC, Tarun-S commented
@wcn00  Could you add a link to the ticket in the description?

2021-03-08 19:25 UTC, Tarun-S commented on avro_to_python_types/schema_mapping.py
> +    "time-millis": "datetime.time",
Similar to Dan's comment above, I think this should be an `int`.

2021-03-08 19:38 UTC, Tarun-S commented on avro_to_python_types/schema_mapping.py
> +    "timestamp-millis": "datetime.datetime",
I think this should also be an `int`, as it's represented in Avro as a `long`.

2021-03-08 20:14 UTC, wcn00 commented on avro_to_python_types/schema_mapping.py
> +    "uuid": "uuid.uuid4",
I agree with you dan.  I will change that.

2021-03-08 20:15 UTC, dangreenisrael commented on avro_to_python_types/schema_mapping.py
> +    "date": "datetime.date",
Maybe it's worth linking to each others' projects. The avro-python ecosystem is pretty sparse.

2021-03-08 20:17 UTC, wcn00 commented on avro_to_python_types/schema_mapping.py
> +    "timestamp-millis": "datetime.datetime",
Regarding the int vs date/datetime... comments.   In the schema the physical type is an int, and it will be an int on the wire.  The logicalType is a date so the avro ser/deser code is expected to convert the wire int to a date/datetime etc.  At least thats how I interpreted the spec.

Just to be sure I'll cook up some unit tests that use the avro python import/export code to actually do some of these conversions.  That'll take  a couple of days cause my confluent install isn't going all that well.

2021-03-08 20:25 UTC, dangreenisrael commented on avro_to_python_types/schema_mapping.py
> +    "timestamp-millis": "datetime.datetime",
Looks like `fast-avro` doesn't support that due to a bug in python. https://github.com/fastavro/fastavro/blob/c25efa0051048cdeda8e5351611642868d51f155/fastavro/_read_py.py#L153-L155

2021-03-08 20:28 UTC, dangreenisrael commented on avro_to_python_types/schema_mapping.py
> +    "timestamp-millis": "datetime.datetime",
It looks like python on windows doesn't allow you to use timestamps for dates that come before the epoc, so `fast-avro` decided to fall back as keeping them as `int`s.

2021-03-08 20:29 UTC, dangreenisrael commented on avro_to_python_types/schema_mapping.py
> +    "timestamp-millis": "datetime.datetime",
Although, it might be worth adding some tests with `fast-avro` to validate that assumption.

2021-03-08 20:31 UTC, dangreenisrael commented on avro_to_python_types/schema_mapping.py
> +    "timestamp-millis": "datetime.datetime",
The apache (slow) avro library does the same thing. https://github.com/apache/avro/blob/7d1e63b219e6d0778bc57195152477adee97fcab/lang/py/avro/schema.py#L1094-L1101

2021-03-08 20:47 UTC, dangreenisrael commented on avro_to_python_types/schema_mapping.py
> +    "timestamp-millis": "datetime.datetime",
Actually, this implies that `avro` does convert to date time. https://github.com/apache/avro/blob/7d1e63b219e6d0778bc57195152477adee97fcab/lang/py/avro/schema.py#L999

2021-03-08 20:49 UTC, dangreenisrael commented on avro_to_python_types/schema_mapping.py
> +    "timestamp-millis": "datetime.datetime",
hmmm. If there is going to be an inconsistency between `avro` and `fast-avro`, we are going to have to call that out in the README.

2021-03-08 20:51 UTC, dangreenisrael commented on avro_to_python_types/schema_mapping.py
> +    "timestamp-millis": "datetime.datetime",
Actually, it's not clear to me what the apache avro library is doing.

2021-03-08 21:02 UTC, dangreenisrael commented on avro_to_python_types/schema_mapping.py
> +    "timestamp-millis": "datetime.datetime",
Actually, I seem to be completely wrong.

https://github.com/fastavro/fastavro/blob/master/fastavro/_read_py.py#L62

🤦  This is embarasing

2021-03-08 21:02 UTC, dangreenisrael commented on avro_to_python_types/schema_mapping.py
> +    "date": "datetime.date",
Looks like I was completely wrong 

https://github.com/fastavro/fastavro/blob/master/fastavro/_read_py.py#L62

2021-03-08 21:03 UTC, dangreenisrael commented
Following up with the confusion around dates, would you mind adding the tests you mentioned using `fast-avro`?

2021-03-09 17:19 UTC, wcn00 commented on avro_to_python_types/schema_mapping.py
> +    "uuid": "uuid.uuid4",
switched to uuid, and tested with fastavro

2021-03-09 18:48 UTC, dangreenisrael commented
Looks like the formatting check is failing. You can fix that by running `poetry run black .`

2021-03-09 22:26 UTC, dangreenisrael commented on tests/test_sync_types.py
> +    def test_synced_types(self):
Will you add a docstring explaining what the test does

2021-03-09 22:27 UTC, dangreenisrael commented
Love the tests 😍

2021-03-09 22:30 UTC, dangreenisrael commented on tests/test_sync_types.py
> +    uuid_of_birth_record: uuid4
I think this is still using the function `uuid4`

2021-03-09 22:31 UTC, dangreenisrael commented on tests/test_sync_types.py
> +from datetime import date
These seem to be duplicated from above

2021-03-09 22:32 UTC, dangreenisrael commented on tests/test_sync_types.py
> +from datetime import date
Lines 7-10, as well as 12

2021-03-09 22:34 UTC, dangreenisrael commented on tests/test_sync_types.py
> +        with open(f"/tmp/nested_type.avro", "wb") as message_out:
NICE 🎉 

Love the round trip test!!!

2021-03-10 14:32 UTC, dangreenisrael commented on tests/test_sync_types.py
> +        records = [
Can we add type hints here
```suggestion
        records: list[ExampleAvroUser] = [
```

2021-03-10 14:34 UTC, dangreenisrael requested changes
Just a few things.

Also, I wonder if this is appropriate time to add MyPy typechecking to the library.

Now that we are actually applying the types in `tests/test_sync_types.py`

2021-03-10 14:34 UTC, dangreenisrael commented on avro_to_python_types/schema_mapping.py
> +    "uuid": "uuid.uuid4",
This is still using the `uuid4` function

2021-03-10 16:10 UTC, wcn00 commented on tests/test_sync_types.py
> +    uuid_of_birth_record: uuid4
done

2021-03-10 16:13 UTC, wcn00 commented on tests/test_sync_types.py
> +from datetime import date
fixed

2021-03-10 16:14 UTC, wcn00 commented on tests/test_sync_types.py
> +        records = [
done

2021-03-10 16:15 UTC, wcn00 commented on tests/test_sync_types.py
> +from datetime import date
gotit

2021-03-10 16:15 UTC, wcn00 commented on tests/test_sync_types.py
> +        records = [
done

2021-03-10 16:28 UTC, wcn00 commented on avro_to_python_types/schema_mapping.py
> +    "uuid": "uuid.uuid4",
Found a few more uuid4's and cleaned up.

2021-03-10 16:41 UTC, Tarun-S commented on tests/test_sync_types.py
> +    def test_synced_types(self):
I don't see the doc strings. Did you push your changes @wcn00?

2021-03-12 16:56 UTC, dangreenisrael commented on tests/test_sync_types.py
> +            to utc when when serializing it.  So if you serialize and deserialize something with a 'niave' datetime
Do you want to open up an issue with fast avro to draw some attention to this? https://github.com/fastavro/fastavro/issues

2021-03-12 16:56 UTC, dangreenisrael approved these changes
Looks great!

2021-03-15 15:09 UTC, Tarun-S commented on avro_to_python_types/typed_dict_from_schema.py
> +                logicaltype = logical_to_pythontype[get_logical_type(field["type"])]
```suggestion
                logical_type = logical_to_pythontype[get_logical_type(field["type"])]
```

2021-03-15 15:09 UTC, Tarun-S commented on avro_to_python_types/schema_mapping.py
> +logical_to_pythontype = {
```suggestion
logical_to_python_type = {
```

2021-03-15 16:42 UTC, eballerini commented
It looks like the [very first commit](https://github.com/waveaccounting/avro-to-python-types/pull/14/commits/ab5fd00332ec124de078286c4663c6783fb9819e) is not signed.

2021-03-16 14:27 UTC, wcn00 commented on avro_to_python_types/typed_dict_from_schema.py
> +                logicaltype = logical_to_pythontype[get_logical_type(field["type"])]
done

2021-03-16 14:27 UTC, wcn00 commented on avro_to_python_types/schema_mapping.py
> +logical_to_pythontype = {
done

2021-03-16 17:51 UTC, Tarun-S approved these changes
LGTM!

2021-03-16 17:55 UTC, wcn00 commented on tests/test_sync_types.py
> +            to utc when when serializing it.  So if you serialize and deserialize something with a 'niave' datetime
I don't think fast avro can do anything about this.  They have to make an assumption about naive datetimes but because they have to serialize and deserialize (potentially not in the same timezone) they can't choose local like datetime's constructor does.  So they are basically at odds with the python lib.  I'd ask them to do something... but I can't imagine what they could do outside of rejecting naive values.
Thoughts?

2021-03-16 18:07 UTC, merged